w	PK     ! ß¤ÒlZ      [Content_Types].xml ¢(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ´”ËnÂ0E÷•ú‘·Ubè¢ª*‹>–-Ré{Vý’Ç¼þ¾QU‘
l"%3÷Þ3VÆƒÑÚšl	µw%ë=–“^i7+Ù×ä-d&á”0ÞAÉ6€l4¼½L60#µÃ’ÍS
Oœ£œƒXø Ž*•V$z3„ü3à÷½Þ—Þ%p)Oµ^ “²×5}nH"dÙsÓXg•L„`´‰ê|éÔŸ”|—PrÛƒsðŽ?˜PWŽìtt4Q+ÈÆ"¦wa©‹¯|T\y¹°¤,NÛàôU¥%´úÚ-D/‘ÎÜš¢­X¡Ýžÿ(¦¼<EãÛ)‘à ;çN„L?¯FñË¼¤¢Ü‰˜¸<FkÝ	‘h¡yöÏæØÚœŠ¤Îqôi£ã?ÆÞ¯l­Îià 1éÓ]›HÖgÏõm @ÈæÛûmø  ÿÿ PK     ! ‘·ï   N   _rels/.rels ¢(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ¬’ÁjÃ0@ïƒýƒÑ½QÚÁ£N/cÐÛÙ[ILÛØj×þý<ØØ]éaGËÒÓ“ÐzsœFuà”]ð–UŠ½	Öù^Ã[û¼x •…¼¥1xÖpâ›æöfýÊ#I)Êƒ‹YŠÏ‘øˆ˜ÍÀå*Döå§i")ÏÔc$³£žqU×÷˜~3 ™1ÕÖjH[{ª=E¾†ºÎ~
f?±—3-ÂÞ²]ÄTê“¸2j)õ,l0/%œ‘b¬
ð¼Ñêz£¿§Å‰…,	¡	‰/û|f\ZþçŠæ?6ï!Y´_áoœ]Aó  ÿÿ PK     ! Öd³Qô   1   word/_rels/document.xml.rels ¢(                                                                                                                                                                                                                                                                  ¬’ËjÃ0E÷…þƒ˜}-;}PBälJ!ÛÖý E?¨,	Íôá¿¯HIëÐ`ºðr®˜sÏ€6ÛÏÁŠwŒÔ{§ ÈrèŒ¯{×*x©¯îAkWkë*‘`[^^lžÐjNKÔõD¢8RÐ1‡µ”d:4e> K/ƒæ4ÆVm^u‹r•çw2NPž0Å®Vwõ5ˆjø¶ošÞàƒ7o:>S!?pÿŒÌé8JX[d“0KDçEVKŠÐ‹c2§P,ªÀ£Å©Àaž«¿]²žÓ.þ¶Æï°˜s¸YÒ¡ñŽ+½·Ÿè(!O>zù  ÿÿ PK     ! Hx­  $3     word/document.xmlì[Koã6¾èÔK4ÑÃòko³yu]Éö\Ð%‘H‚¤­MŠþ÷)Év6]ÉÙ,&Ë‹%QÃ™o†3ßH„üæí§²p6XHÂèÜŽ}×Á4f	¡ÙÜýóãÅÑÄu¤B4A£xîÞbé¾]üøÃ›j–°x]bªPAå¬âñÜÍ•â3Ï“qŽK$K&YªŽcVz,MIŒ½Š‰ÄýÀ7g\°K	öNÝ é6êÊ‡ÚÇn¦L”HÁ¥È¼‰›5?í)²"Q· ÛµjØÜ]:kTmé)³PshgˆCìÖSÎš‹žÀ``Tæ„ïÜøZmp3o•lºœØ”E+Wñ zÚœ	TÁa§ðøI=©,jäÝÿ€Ñ*¶3pßf‹¤D„îUhö‚§ ü\Ïž¶8—‚­ùNyš¶÷ôf«KWö#t5‹¼ïš|˜ëq¨À2ž½Ï(hU "X2¢îè´vÀ8+–Üê#wª0Vr5w}2!ÐV3´zð$¿^lÏpŠÖ…z(¾Ü2š—BZÉæ‚TÌÝ§JÏâ\#×ë&ƒ°["G“n‰ÁhuKDÃ‰ß-1Œ¦=HGQÐƒt<{NÂ¨)¬iàûã¾ úÓiÖ ˜ú=`ƒàöˆÆQÜh44p½]¶HŽbÈeA©Â:µxAtu…Ñöâj­“­«Mšè; ]»Ø®¨¨3Q\0ª¤V)cÊÖ‚`á|À•Ö‡‘T'’ ¹û‘”XêaçŠ•ˆê›ù	•§Äòþ±&ïZ/ÃÆ¾¼;Õf÷Æ¼”·-¨_–žrê–ƒS™@åµBB5>8ÿU”ÿoïÀ•E\ )ÍÊÖã_ôõœ&/ÚSMß&mÁ.°ÄbƒÝ…s)0†¾½ê&­§–{-÷Zî}6îÎkb§m%ÇE±×Z^këIpzP(¶ç{êK„EPAîðÏUÎ~±ý©CÂö'ÛŸlúfýÉq~ÊqæüZÞ±¼³±¼cyçùž‹_Éc/¦É!ž6Ïµ–s-çZÎµœk÷"ì^ÄseI¦÷Èí›@‡„íJ¶+Ù®ôw ÜßlÙ¯ßË;ÁO?â•àåº©÷•þqm'é°ÄvÛIìžÒ£¼·{J–s-çÚo_(+…a8ôÇÑHÏX1v£ÿaB¢$ir†¢lüuÉÞ¡ø¦FÜÊž›l©%÷ŒK«å6Þ{²ìZG ÒÉß$bçÃI›å<ûß×54ˆp’å€x24VL)Vîî6ù:ö££Dgüª.SÆL4—ÙZ5õ`¬Å¬ÐÁoºž–1Ã	‹/1µ U²$*Î5	¶nÖšÓúso÷÷–Å¿   ÿÿ PK     ! ªR%ß#  ‹     word/theme/theme1.xmlìYM‹7¾úÄÜÍøc‰7Øc;i³›„ì&%GyFžQ¬IÞ]%9
¥ié¡Þz(m	ô’þšmSÚòªÑxlÉ–YÚl`)YÃZÏûêÑûJ4žËWNŽã˜¦§z©â ”4ÄiÔqîK-pÓš¢Ž3GÜ¹²ûá—áŽˆQ‚€´Oùì8±Ór™²òKtŠRÙ7¦,BVYT<–~R®U*rqê€&ÒíÍñf.ÝÂù€È©àYC@ØAæ
NªÙŸsŸ0pIÇ‘ã„ôøÈ…ìè8õç”w/——FDl±Õì†êoa·0'5eÇ¢ÑÒÐu=·Ñ]úW "6qƒæ 1h,ý) 9Óœ‹Žõzí^ß[`5P^´øî7ûõª×ü×7ð]/ûxÊ‹î~8ôW1Ô@yÑ³Ä¤Yó]¯@y±±oVº}·ià(&8l +^£î³]BÆ”\³ÂÛž;lÖðª¬­®Ü>ÛÖZïS6” •\(p
Ä|ŠÆ08<bìá(–o
SÊes¥VVêòöqUIEî ¨YçMßhÊø 0<çcéÕÑ o^þøæåspúèÅé£_N?>}ô³ÅêL#Ýêõ÷_üýôSð×óï^?ùÊŽç:þ÷Ÿ>ûí×/í@¡_}ýìÏ^}óùŸ?<±À»Žtø!N7Ð1¸M91Ë hÄþÅa±nÑM#S˜ÙXÐèsH ×Cfï2)6àÕÙ}ƒðAÌf[€×ãÄ îSJz”Yçt=KÂ,ìƒ³™Ž»á‘ml-¿ƒÙT®wlséÇÈ y‹È”Ã¥H€¬N²˜ÝÃØˆë>åt,À=z[CrˆGÆjZ]Ã‰ÌËÜFPæÛˆÍþ]Ð£Äæ¾ŽL¤ÜØ\"b„ñ*œ	˜XÃ„èÈ=(bÉƒ9Œ€s!3!BÁ DœÛln²¹A÷º”{Ú÷É<1‘Là‰¹)Õ‘}:ñc˜L­œqëØøD.QnQa%AÍ’Õe`º5Ýw12Ò}öÞ¾#•Õ¾@²ž³m	DÍý8'cˆ”óòšž'8=SÜ×dÝ{·².…ôÕ·Oíº{!½Ë°uG­Ëø6Üºxû”…øâkwÎÒ[Hnô½t¿—îÿ½toÛÏç/Ø+V—øâª®Ü$[ïícLÈ˜´Ç•ºs9½p(UE-¦±,.†3pƒªŸ`Äp*‡©ª"¾pq0¥\žªÙê;ë ³dŸ†ykµZ<™J(Víò|)Úåi$òÖFsõ¶t¯j‘zT.d¶ÿ†„6˜I¢n!Ñ,Ï ¡fv.,Ú­ÌýVêk‘¹ÿ Ì~ÔðÜœ‘\o 0ËSn_d÷Ü3½-˜æ´k–éµ3®ç“iƒ„¶ÜLÚ2ŒaˆÖ›Ï9×íUJzY(6i4[ï"×™ˆ¬iIÍ8–{®îI7œvœ±¼Êb2•þx¦›DiÇ	Ä"ÐÿEY¦Œ‹>äqS]ùü,'r­ëi éŠ[µÖÌæxAÉµ+/rêKO2Q ¶´¬ª²/wbí}KpV¡3Iú ÁˆÌØm(å5«Y CÌÅ2š!fÚâ^EqM®[ÑøÅlµE!™Æpq¢èbžÃUyIG›‡bº>+³¾˜Ì(Ê’ôÖ§îÙFY‡&š[ìÔ´ëÇ»;ä5V+Ý7XåÒ½®uíBë¶o hÔVƒÔ2Æj«V“Ú9^´á–KsÛqÞ§ÁúªÍˆâ^©j¯&èè¾\ù}y]ÁUt"ŸüâGå\	Tk¡.'Ìî8*^×õkž_ª´¼AÉ­»•RËëÖK]Ï«W^µÒïÕÊ ˆ8©zùØCù<Cæ‹7/ª}ãíKR\³/4)Su.+cõö¥ZÛþö`™Ú°]o÷¥v½;,¹ý^«Ôö½R¿á7ûÃ¾ïµÚÃ‡8R`·[÷ÝÆ UjT}¿ä6*ýV»Ôtkµ®Ûì¶n÷á"ÖræÅw^Åk÷   ÿÿ PK     ! ’[;)¸  á	     word/settings.xml´VÛŽÛ6}/Ð0ô\­eùºj¼AlÇÍë¦ˆœ DÊ&–7”½NÑïWöf¸òdjÎÜyfè7oŸ8ëˆ6TŠy4¸I¢¥ÄTìæÑ—í:žE=c‘ÀˆIAæÑ‰˜èíÝ¯¿¼9f†Xj¦.„Éx9öÖª¬ß7åžpdn¤"ÀJjŽ,|ê]Ÿ#ýX«¸”\!KÊ¨=õÓ$™D­9j-²ÖEÌi©¥‘•u&™¬*Z’ö'Xèkâ6&+YÖœë#ö5aƒfO•	Þøÿõà>89|¯ˆgAï8H®(÷(5~¶¸&=g ´,‰1pAœ…©è¾qôûb·%zW`>Hüé<óñs¾p`Ø5•4Ð-4ÒOÚ2x™Ýï„Ô¨`ÀJ(§Ew@Ë¯RòÞ1SD—p7Àé$‰ú€ŽÈ*·È€"Œy’—Œ pxÌvq gxL*T3»EEn¥¥‚¼§ië²Ü#JKt®P	Þ–RX-YÐÃòOi—@u7ÑZxâw§¼"°ˆC%ƒ±‘˜¸ÌjM¯o¶3ðÑ¡g!_’0ôšb²uÌí‰‘5$ŸÓ¯äÀkc)xôãñ|/"\äOpçÛ“"k‚lmúIÁüM¬UªµÔ÷7~Z0ZUDC 
\Û }¨–GßçaØµ?·N#ØÜØ„Ãg)mPM’ÛwÉbuÛdêÐÝN†ëÅkÈx2˜½Ÿ¾†ÌfÃAàý%ÒÅé?çÃ3·ÿÒáäÈÕãÅñBSÔÛ¸Ùw…~\Pð‚À
 çH^Œã01¶†é€Og˜µ"•?³Ò»Îo«¡_•Â¤|öå6ÑhY«=j¤Ò•ÁhÔZRa(rSy°°´Î ZàOíûÔµç˜Y¸|?|È“ÈëÉ[’1;‚RªáY±Ì#Fw{;pÔ°ð…áaõÅ.m±ÔciƒùTºÊ@»=t²4ÈÎô†A6ìd£ u²q;Ù$È&N¶‡	×°nòáèä•dL	þÐáßˆš&˜=RdÕlc —líz6½CFž`×L-ü_QsôäV:qæ­6C'YÛ]‡9eué#‹Â°]{Š¿ÈÅ½%:æ'^tËÿ·&qF,ï„•:`¿{l0öˆÝ‹áb?“jÁ-†eyÝ³ÖØü=ž¦“)¼Äñ$]¯âÑb6‰oßOÇñrºJÃÅp:ZŽÿi§0ü7»û  ÿÿ PK     ! •Ï’ìé  ù     word/fontTable.xmlÄ“ßnÚ0‡ï'í"ß—8Ú‚*–iÒ´‹ª{ ã8ÄšÿD>†”·ß±Ù&Š
š´)
¿cä<<¾j•ì„iMA²%‰0ÜVÒl
òýeusOðÌTLY#
²@?<tóÚ	î70×¼ ÷í<M7B3ÙV,ÖÖiæñ«Û¤š¹Ûö†[Ý2/×RI¿OsJoÉã.¡Øº–\|¶|«…ñqê„B¢5ÐÈŽ´îZg]Õ:Ë žY«ž§™4&›œ€´äÎ‚­ýsè(¢p{Fã“V¿ Óë ù Ð|þec¬ck…ò±“adq°ŸtsÃ4J¦äÚÉXh™± 2¬í˜*ÍéŠNñ>:w’†…¼aD€Ä…eÙÇ5ÓRí)t /´Òóæ˜ï˜“¡©¾rƒ…-¬iAž(^ùjEú$+Èƒe9$96Õ_Ù!		œ~Å,îâ‘3¬ÁßL{'&^¤|]òl53gŒäôMLÑG03¾Êˆ‹ÜkäO¿)1¹»ŸŒOŒÌÞ7Òs.7RÚ­“Â'glÜ¡Y´lL®²¡m%Ü[:jù*ª3.–ÿÍE?'ÉW¹iüÙi	3ò¯¦eZÆ—ãÏiÁÿäÓ‰xú¿œ–Ã,~  ÿÿ PK     ! [mý“	  ñ     word/webSettings.xml”ÑÁJ1à»à;,¹·ÙYº-ˆT¼ˆ >@šÎ¶ÁL&Ì¤®õék­H/õ–I23ü“Ù;ÆêX¥ÖŒ†µ© yZ†´jÍËó|pm*).-]¤­Ù‚˜ÙôülÒ7=,ž ý)•*Iô­Y—’kÅ¯)CÒÇŽ]Ñ’W¿nòÀfWÂ"ÄP¶v\×WfÏð)
u]ðpK~ƒÊ®ß2D)É:dùÑúS´žx™™<ˆè>¿=t!˜ÑÅ„Á3	ue¨Ëì'ÚQÚ>ªw'Œ¿Àåÿ€ñ@ßÜ¯±[D@'©3SÍ€r	>`N|ÃÔ°ýºv1Rÿøp§…ýÔô  ÿÿ PK     ! fæÁG{  Õ   docProps/app.xml ¢(                                                                                                                                                                                                                                                                  œRËNä0¼#ñQîŒÃJ „zŒÐ â ËH	ÃÙ²;‰µ~É6ˆüý¶ÉÍjo{ëªv—«Ë†›OkªŒI{·­Ï7M]¡“^i7lë×îáìª®RN	ãnë	S}ÃOO`}À˜5¦Š$\ÚÖcÎáš±$G´"m¨í¨ÓûhE&æû^K¼óòÝ¢ËìGÓ\2üÌèª³°Ö³âõGþ_Qåeñ—ÝHC‡6‘‘ÿ,“f£|¶À:Ÿ…é´EÞ½ Ø‹?6ðæ£"|l®`7Š(d¦ ùÕ%°„ÛŒ–"S²üYËè“ïsõòe·*ãÀÖG€VhQ¾G§âbáI»ÙÇ\¯(†(Âx4· h¥0¸£åy/LB`Øy„›øýþö¹j§”Ñ&ò|dË%¿Òkèü]Éä8þ7¹Ú÷Mç±B_M³^}Õ–XT´Ëbg!à‘'š¢O³n@õ}æßF	ó0ÿRJÓ4åÆG,ß‡ÿ  ÿÿ PK     ! Ì$p  ï   docProps/core.xml ¢(                                                                                                                                                                                                                                                                  œ’QOƒ0…ßMü¤ï¬À¦qX2Í—˜8£ñ­kï¶:h›¶òï-0˜èž|»·ç»‡Ëi“ÙW‘{GÐ†K‘¢p •Œ‹mŠ^WÿyÆÁH.¤¨ƒfÙõUBUL¥†g-hËÁxÎI˜˜ªí¬U1Æ†î  fäáÄÔ±®Õ[¬Ý“-à(nq–0b	®}Õ;¢“%£½¥:è¼1`Ckp8
ñ™µ sq Q~·•‚‹h'öô—á=X–å¨7¨Û?ÄïË§—æW}.ê¬( ,a4¶Üæ%ø\ºÊÖŸ@m{Ü7®¦ˆ•:{Ô• Þœ¬+ºk N¨#ßCUJÍŒtc`¨æÊº‹lÍŽÎ‰±Kw³l^ýúÎ_½ÑpäõËÈ¢†èÛäs»0ÏÅ·avÊÛøþaµ@Y„7~0ñ£ñ*˜Æ“iõzƒù³aqZàßŽA›Ðð‰fß   ÿÿ PK     ! Ü™óA+  p     word/styles.xml¼]sÛº†ï;ÓÿÀÑU{áÈòw<Ç9c;qãiœã9Í5DBjPùÇýõ@J‚¼Å·¾²%j‚x÷°ü~ûýW*£Ÿ</„Ê.F“wû£ˆg±JDöx1úþp³w6ŠŠ’e	“*ã£^Œ~ÿð×¿üö|^”/’‘dÅy_Œe¹<‹xÁSV¼SKžés•§¬Ô/óÇqÊò§j¹«tÉJ1R”/ãƒýý“QƒÉûPÔ|.bþQÅUÊ³ÒÆs.5QeÅB,‹í¹íYåÉ2W1/
}Ð©¬y)Ù39 TÄ¹*Ô¼|§¦i‘EéðÉ¾ý/•À1p°¤ñùíc¦r6“º÷uK"}ÐÝŸ¨ø#Ÿ³J–…y™ßçÍËæ•ýs£²²ˆžÏYñ ÷¬!©Ð¼Ï—Y!FzgEyYÖºqaþiÝ¥óö•HÄhlöXüWoüÉäÅèà`õÎµiÁÖ{’e«÷x¶÷}ê¶Äyk¦¹#–ïM/Mà¸9°ú¯s¸Ë×¯ìŽ—,v?l^rY““}•Â$òÁñûÕ‹o•é[V•ªÙ‰Ô×Ø1èqp:ý¦µôV>ÿ¢â'žLK½ábd÷¥ßü~{Ÿ•ëL¿½·ûÔoNy*>‹$á™óÁl!þcÁ³ïO6ïÿyc³µy#VU¦ÿ?<Ø,EòéWÌ—&÷õÖŒM¾š i>]‰ÍÎmøV°I£D[ü‚33 D“×Û|âÀDÎÑ¶3«WÇn?…ÚÑá[íèè­vtüV;:y«¾ÕŽÎÞjGóÿÜ‘Èþ«6"Ü îâxÜˆæxÌ†æx¼„æx¬‚æxœ€æxÍñä1šãIS§T±/d?ôd{7w÷ÆÝ=%„qwÏ aÜÝ~w÷øÆÝ=œ‡qwÞaÜÝƒ5ž[/µ¢[m³¬ì²¹Re¦J•ü×pË4ËVE4<3éñœä 	0õÈÖLÄƒi1³¯wgˆ5iø|^šB.Róh.«\ÓCÎ³Ÿ\ê²6bI¢y„Àœ—Uîé‘œÎùœç<‹9ebÓAM%eU:#ÈÍ%{$cñ,!î¾‘dPX'´®ŸÆ$‚ ©SçjxÓ#¾ˆbx_HtUIÉ‰X_iRÌ²†×3¼4°˜á•Å/Í¨º¨¡õTC#ê°†FÔou~Rõ[C#ê·†FÔomx¿=ˆRÚ!Þ]uLúŸ»»–ÊœÇÜŽ©xÌ˜^ Ÿnšs¦Ñ=ËÙcÎ–‹Èœ•nÇºÇŒÝÏ•J^¢Š9mM¢Z×Û¹ÖG-²jx‡nÑ¨ÌµæÙkÍ#2Øš7Übwz™lhŸiê™i5+[MkI½L;e²ª´ÃÝÆÊá¶1ÀÈ2´c	2ø«YÎ9)F¾M+‡7lÃn«×£ió$A+¥ŠŸh†áÏ/Kžë²ìi0éFI©žyBGœ–¹ªsÍµü•¤—å?¥Ë+„­•¶ý§úÕðèŽ-Ð½d"£ÑíÓ^Ê„ŒèVŸî¾DjiÊLÓ14À+U–*%c6gÿöƒÏþNÓÀK]g/DG{ItzÈÂ®Á$S“TBDÒËL‘	’9ÔòþÉ_fŠå	í>çõM'%'"NYº¬ÞÒãâ³VC–÷/–s^ˆÊT$0ç´aQÍþÍãáCÝW‘œú£*íùG»ÔµÑt¸áË„-Üð%‚USO&	v7ü`·pT{-YQï%Ô`Õá®xÔÇ;¼økxJª|^Iº\Ézp$ëB%«4+(ØòØò¨—0e,à”œåý#	™F¥„…QÉ`aTX© ÃïÐq`ÃoÓq`ÃïÕ©aDK F•g¤Ó?ÑUF•gF•gF•gF•g‡#>ŸëE0Ýã ©rÎAÒM4YÉÓ¥ÊYþB„ü$ù##8AZÓîs57O#¨¬¾‰› iÎQKÂÅv£ùŸ‘5Í°(ÛEpF”I©Ñ¹µÍ„c#·ï]ÛfŸäÜ„{Éb¾P2á¹ç˜ü±º^žÖe¼n¾mF¯Óž_Äã¢Œ¦‹õÙ~s²¿3rU°o…íÞa[ŸŸ¬žgi»ã‰¨ÒUCáÃ'‡ýƒmFoíÞ¬$¶"{FÂ}žìŽÜ¬’·"O{FÂ}žõŒ´>ÝŠìòÃG–?µ&ÂiWþ¬k<OòveÑ:¸u·]‰´ŽlKÁÓ®,Ú²JtÇæjT§ŸgüñýÌãÇ¸ÈOÁØÉOéí+?¢Ë`ßøOafvÌ i÷·¾{ŒûvÝkäü³Rõyû­NýêºÕ§¬àQ+ç°ÿ…«­QÆß½‡?¢÷¸ãGô€üˆ^#‘75$ù)½Ç&?¢÷ åG G+8#àF+­`|Èh)!£Õ€U€Ñ{9àG 
h£X)ø(£‚ð £B
Ú¨6*D 
`8£ÂxœQa|ˆQ!%Ä¨‚6*D 
h£BÚ¨6jàÚÞdTHA"ÐF…´Qízq€Qa<Î¨0>Ä¨bTHA"ÐF…´Q!mTˆ@"PFáAF…´Q!mTˆ@µ~Ô0Ü¨0gTbTH	1*¤ 
h£BÚ¨6*D 
(£‚ð £B
Ú¨6*D j/0*ŒÇÆ‡RBŒ
)h£BÚ¨6*D 
h£BÊ¨ <È¨‚6*D 
]ùÙ\¢ôÝf?ÁŸõôÞ±ßÿÒUÓ¨oî£Ü.ê°?jÕ*?«ÿ³WJ=E­Úz£DÌ¤Pöµç²ºËµ·D .|þqÝý„Kø¥KÍ³öš)€õçTŽºRÞEÞQW¦»‘`ÕyÔ5úº‘`<êt­/W7¥èéw3NðÄÞ5Z;á°‹»Æh'öp×ÈìÂîÀãÈÎ¯£{öÓÉúþR@èJG‡pê't¥%Ôj5CcôÍOè«žŸÐWF?¥§ƒÖB+ìG…Im†•:Ü¨~VjH’`Â¥†¨`©!*Lj80b¥†¬Ôáƒ³Ÿ$5À„KQÁRCT˜Ôp*ÃJ	X©!+õÀ	Ù‹	—¢‚¥†¨0©áâ+5$`¥†¬Ô$5À„KQÁRCT˜Ô JFK	X©!+5$I0áRCT°ÔÕ%µ=‹²%5Ja'·sq²ˆœÀ€jÉ‰¬–B`µµZiŽ«–\Ñü„¾êù	}eôPzz1xaý(´Â~T˜Ô¸j©Mêp£ú	X©qÕ’Wj\µÔ)5®Zê”W-ù¥ÆUKmRãª¥6©Ãg?!Hj\µÔ)5®Zê”W-ù¥ÆUKmRãª¥6©qÕR›Ô'd/&\j\µÔ)5®ZòK«–Ú¤ÆUKmRãª¥6©qÕ’Wj\µÔ)5®Zê”W-ù¥ÆUKmRãª¥6©qÕR›Ô¸jÉ+5®Zê”W-uJí©–ÆÏ[?ÀdØöÉô‡Ë—%7ßÁí<0“ÔßAÚ\´¼MÖ?”d‚MK¢æ'©š·mƒ›†öÿ¼ÐU]ó™ýý³³ÃÉí¡qƒ„ˆºqó½JžF4ßº~ÀÇ~;êë&y¾DÕ6kÓ9«O7½¹HZnë‚hg»K#FG›­X½Wëékàû&AwµP·g&ëŸóÒÿÜf¦ûŸ›Ÿ²ª[šüb5Jo¿æRÞ±úÓjéÿ¨äó²Þ:Ù·Ó¿Ú>«¿ÎŸÛ!Äo7¦~Ùü¤˜§¿ëïŠo®m{“Õø¤¥»íC{zÓ¶ÕÅ‡ÿ  ÿÿ PK-      ! ß¤ÒlZ                      [Content_Types].xmlPK-      ! ‘·ï   N               “  _rels/.relsPK-      ! Öd³Qô   1               ³  word/_rels/document.xml.relsPK-      ! Hx­  $3               é  word/document.xmlPK-      ! ªR%ß#  ‹               4  word/theme/theme1.xmlPK-      ! ’[;)¸  á	               Š  word/settings.xmlPK-      ! •Ï’ìé  ù               q  word/fontTable.xmlPK-      ! [mý“	  ñ               Š  word/webSettings.xmlPK-      ! fæÁG{  Õ               Å  docProps/app.xmlPK-      ! Ì$p  ï               v  docProps/core.xmlPK-      ! Ü™óA+  p                  word/styles.xmlPK      Á  u+    